-- Boutique Senegal: schema Supabase. Execute once in Supabase SQL Editor.
create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact text default '', phone text default '', email text default '', address text default ''
);

create table if not exists sellers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text default '', email text default '', active boolean not null default true
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text default '', email text default '', address text default ''
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text default '', purchase_price numeric not null default 0,
  sale_price numeric not null, stock integer not null default 0,
  min_stock integer not null default 0,
  supplier_id bigint references suppliers(id), created_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null, password_hash text not null,
  role text not null check (role in ('admin', 'seller')),
  seller_id bigint references sellers(id), active boolean not null default true
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), seller_id bigint references sellers(id),
  client_id bigint references clients(id), total numeric not null, discount numeric not null default 0,
  paid numeric not null, payment_method text not null
);

create table if not exists sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references sales(id) on delete cascade,
  product_id bigint not null references products(id), quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0)
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), label text not null, amount numeric not null check (amount >= 0)
);

alter table suppliers enable row level security;
alter table sellers enable row level security;
alter table clients enable row level security;
alter table products enable row level security;
alter table users enable row level security;
alter table sales enable row level security;
alter table sale_items enable row level security;
alter table expenses enable row level security;

-- The Streamlit server uses the secret server key stored in its private Secrets.
-- No client/browser key receives write access to these tables.

-- Boutique Senegal V2: migration non destructive. Ce bloc peut être exécuté
-- sur une base existante dans Supabase SQL Editor.
alter table products add column if not exists barcode text;
alter table products add column if not exists photo_url text default '';
alter table sales add column if not exists due_date date;
create unique index if not exists products_barcode_unique
  on products(barcode) where barcode is not null and barcode <> '';

-- Espace public pour les photos de produits. Les téléversements sont effectués
-- uniquement par le serveur Streamlit avec sa clé privée service_role.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists credit_payments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  client_id bigint not null references clients(id),
  sale_id bigint references sales(id), amount numeric not null check (amount > 0),
  payment_method text not null, recorded_by bigint references users(id)
);

create table if not exists cash_closings (
  id bigint generated by default as identity primary key,
  closing_date date not null, seller_id bigint references sellers(id),
  expected_cash numeric not null default 0, counted_cash numeric not null default 0,
  difference numeric not null default 0, notes text default '',
  closed_by bigint references users(id), created_at timestamptz not null default now()
);

create table if not exists activity_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), user_id bigint references users(id),
  action text not null, details text default ''
);

create table if not exists inventory_counts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), product_id bigint not null references products(id),
  expected_stock integer not null, counted_stock integer not null,
  difference integer not null, counted_by bigint references users(id), notes text default ''
);

create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null unique, address text default '', phone text default '', active boolean not null default true
);
insert into stores(name) values ('Boutique principale') on conflict do nothing;

create table if not exists store_stock (
  store_id bigint not null references stores(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  stock integer not null default 0 check (stock >= 0),
  primary key(store_id, product_id)
);

create table if not exists stock_transfers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), product_id bigint not null references products(id),
  from_store_id bigint not null references stores(id), to_store_id bigint not null references stores(id),
  quantity integer not null check (quantity > 0), transferred_by bigint references users(id), notes text default ''
);

create table if not exists shop_settings (
  id integer primary key default 1 check (id = 1), shop_name text not null default 'Boutique Senegal',
  phone text default '', address text default '', logo_url text default '',
  receipt_footer text default 'Merci pour votre achat !', currency text default 'FCFA'
);
insert into shop_settings(id) values (1) on conflict (id) do nothing;

alter table credit_payments enable row level security;
alter table cash_closings enable row level security;
alter table activity_logs enable row level security;
alter table inventory_counts enable row level security;
alter table stores enable row level security;
alter table store_stock enable row level security;
alter table stock_transfers enable row level security;
alter table shop_settings enable row level security;

-- Boutique Senegal V3 : documents, fournisseurs, retours, caisse, fidélité,
-- permissions, lots et synchronisation des ventes hors connexion.
alter table sale_items add column if not exists unit_cost numeric;
update sale_items si set unit_cost = p.purchase_price
from products p where p.id = si.product_id and si.unit_cost is null;
alter table clients add column if not exists loyalty_points integer not null default 0;
alter table clients add column if not exists store_credit numeric not null default 0;
alter table users add column if not exists can_view_stock boolean not null default false;
alter table users add column if not exists can_discount boolean not null default false;
alter table users add column if not exists can_returns boolean not null default false;
alter table users add column if not exists can_credit boolean not null default false;

create table if not exists documents (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  document_type text not null check (document_type in ('DEVIS','FACTURE','BON_LIVRAISON')),
  status text not null default 'BROUILLON', client_id bigint references clients(id),
  valid_until date, notes text default '', total numeric not null default 0,
  created_by bigint references users(id)
);
create table if not exists document_items (
  id bigint generated by default as identity primary key,
  document_id bigint not null references documents(id) on delete cascade,
  product_id bigint not null references products(id), quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0)
);
create table if not exists purchase_orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), supplier_id bigint not null references suppliers(id),
  expected_date date, notes text default '', total numeric not null default 0,
  paid numeric not null default 0, status text not null default 'COMMANDÉE',
  created_by bigint references users(id)
);
create table if not exists purchase_order_items (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references purchase_orders(id) on delete cascade,
  product_id bigint not null references products(id), quantity integer not null check (quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  unit_cost numeric not null check (unit_cost >= 0)
);
create table if not exists supplier_payments (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  purchase_order_id bigint not null references purchase_orders(id), amount numeric not null check (amount > 0),
  payment_method text not null, recorded_by bigint references users(id)
);
create table if not exists returns (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  sale_id bigint not null references sales(id), product_id bigint not null references products(id),
  quantity integer not null check (quantity > 0), reason text default '',
  resolution text not null check (resolution in ('REMBOURSEMENT','AVOIR','ECHANGE')),
  refund_method text default '', refund_amount numeric not null default 0,
  processed_by bigint references users(id)
);
create table if not exists cash_movements (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  movement_date date not null, movement_type text not null check (movement_type in ('ENTREE','SORTIE','FOND_INITIAL')),
  amount numeric not null check (amount > 0), label text not null, recorded_by bigint references users(id)
);
create table if not exists product_lots (
  id bigint generated by default as identity primary key, created_at timestamptz not null default now(),
  product_id bigint not null references products(id), batch_number text not null,
  expiry_date date not null, quantity integer not null default 0 check (quantity >= 0), notes text default '',
  unique(product_id,batch_number)
);
create table if not exists offline_imports (
  id bigint generated by default as identity primary key, offline_id text not null unique,
  imported_at timestamptz not null default now(), imported_by bigint references users(id),
  original_created_at timestamptz
);

alter table documents enable row level security;
alter table document_items enable row level security;
alter table purchase_orders enable row level security;
alter table purchase_order_items enable row level security;
alter table supplier_payments enable row level security;
alter table returns enable row level security;
alter table cash_movements enable row level security;
alter table product_lots enable row level security;
alter table offline_imports enable row level security;

-- Réaligne les compteurs après une restauration qui conserve les identifiants.
create or replace function public.sync_boutique_sequences()
returns void language plpgsql security definer set search_path = public as $$
declare table_name text; sequence_name text; maximum_id bigint;
begin
  foreach table_name in array array['suppliers','sellers','clients','products','users','sales','sale_items','expenses','credit_payments','cash_closings','activity_logs','inventory_counts','stores','stock_transfers','documents','document_items','purchase_orders','purchase_order_items','supplier_payments','returns','cash_movements','product_lots','offline_imports'] loop
    sequence_name := pg_get_serial_sequence('public.' || table_name, 'id');
    if sequence_name is not null then
      execute format('select max(id) from public.%I', table_name) into maximum_id;
      perform setval(sequence_name, coalesce(maximum_id, 1), maximum_id is not null);
    end if;
  end loop;
end;
$$;
revoke all on function public.sync_boutique_sequences() from public;
grant execute on function public.sync_boutique_sequences() to service_role;

-- Demande à l'API Supabase/PostgREST de reconnaître immédiatement les
-- nouvelles tables et colonnes, sans attendre le rafraîchissement du cache.
notify pgrst, 'reload schema';
