-- Boutique Senegal: schema Supabase. Execute once in Supabase SQL Editor.
create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact text default '', phone text default '', email text default '', address text default ''
);

create table if not exists sellers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text default '', email text default '', active boolean not null default true
);

create table if not exists clients (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text default '', email text default '', address text default ''
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text default '', purchase_price numeric not null default 0,
  sale_price numeric not null, stock integer not null default 0,
  min_stock integer not null default 0,
  supplier_id bigint references suppliers(id), created_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null, password_hash text not null,
  role text not null check (role in ('admin', 'seller')),
  seller_id bigint references sellers(id), active boolean not null default true
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), seller_id bigint references sellers(id),
  client_id bigint references clients(id), total numeric not null, discount numeric not null default 0,
  paid numeric not null, payment_method text not null
);

create table if not exists sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references sales(id) on delete cascade,
  product_id bigint not null references products(id), quantity integer not null check (quantity > 0),
  unit_price numeric not null check (unit_price >= 0)
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(), label text not null, amount numeric not null check (amount >= 0)
);

alter table suppliers enable row level security;
alter table sellers enable row level security;
alter table clients enable row level security;
alter table products enable row level security;
alter table users enable row level security;
alter table sales enable row level security;
alter table sale_items enable row level security;
alter table expenses enable row level security;

-- The Streamlit server uses the secret server key stored in its private Secrets.
-- No client/browser key receives write access to these tables.
